### DISCUSSION TITLE
Solutions to toggle non-internal touchpads, similar to palm exclusion and disable while typing

### DISCUSSION THREAD

**Discussion by digitalsignalperson** [iberianpig/fusuma#297] [General]
I'm using a bluetooth magic trackpad 2, and features like palm exclusion zones, disable while typing etc. are not implemented and this is not something libinput will implement for external devices: https://gitlab.freedesktop.org/libinput/libinput/-/issues/874

per that thread, I tried tweaking some udev rules and libinput quirks to no avail.

With my touchpad right below my keyboard spacebar, I constantly hit it with my palm and it moves the cursor and clicks things all the time. So I need some way to disable it automatically or manually.

Here's a solution that kind of works

```
swipe:
  4:
    up:
      command: "xinput enable \"Apple Inc. Magic Trackpad 2\""
    down:
      command: "xinput disable \"Apple Inc. Magic Trackpad 2\""
```

swipe up to enable trackpad,
swipe down to disable

Not ideal since that's a lot to do for any touchpad interaction, but it does let me actually use the keyboard and rest my hands down normally.

Another idea could be to have some kind of timer that will disable the trackpad N seconds after the last interaction. A script could probably monitor xinput messages right now or the `fusuma -v` output to control such a timer with.

I'm also considering making something like "ctrl key must be held down to use the touchpad".

I'm curious if anyone here has suggestions or experiences here, thanks.

**Comment by digitalsignalperson** [comment]
here's something I just whipped up: https://gist.github.com/digitalsignalperson/34c1df16fdcd4b87c873aaba29d70b22

using with config:

```
swipe:
  3:
    up:
      command: "/path/to/disable-trackpad-timeout.py"
```

this works like:
- swipe up to enable trackpad
- N seconds after last trackpad event, disable trackpad
