### DISCUSSION TITLE
weird swipe behaviour

### DISCUSSION THREAD

**Discussion by ggrrll** [iberianpig/fusuma#338] [General]
hi, 

thanks again for the tool

here is my config

```
swipe:
  3:
    left:
      command: "xdotool key alt+Left" # History forward
    right:
      command: "xdotool key alt+Right" # History back
  4:
    left:
      command: "xdotool key ctrl+alt+Left" # Switch to next workspace
    right:
      command: "xdotool key ctrl+alt+Right" # Switch to previous workspace
    up:
      command: "xdotool key ctrl+alt+Up" # show windows in workspace
    down:
      command: "xdotool key ctrl+alt+Down" # show all workspaces
pinch:
  in:
    command: "xdotool keydown ctrl click 4 keyup ctrl" # Zoom in
  out:
    command: "xdotool keydown ctrl click 5 keyup ctrl" # Zoom out
hold:
  4:
    command: "xdotool key super" # Activity
```

when I  swipe up with 4 fingers and back down, it goes to the left ...  there is a conflict with something else:

if I  stop `fusuma` (and removed `touchegg`) indeed there is still a swipe behavior  ... any idea what else in **Mint/cinnamon** can control it ?

thanks

specs:
* des. env. : cinnamon  6.0.4
* OS: Linux Mint 21.3 Cinnamon
