### ISSUE TITLE
Assign command with combination of key press and gesture

### ISSUE THREAD

**Issue by iberianpig** [iberianpig/fusuma#105]
I want to assign command to combination of key press and swipe event.

To move current window to another workspace, however number of gesture only 3/4 swipe/pinch is not enough.

## ex) Move current window to another Workspace
 - Shift + 3 finger swipe left = move window to previous workspace
 - Shift + 3 finger swipe right = move window to next workspace

## ex) Brightness Controll
- Shift + 3 fingers swipe up = Brightness Up
- Shift + 3 fingers swipe down = Brightness Down

## ex) Volume Controll
- Alt + 3 fingers swipe up = Volume UP
- Alt + 3 fingers swipe down = Volume Down

**Comment by iberianpig** [comment]
will support `key_xxxx` properties on `config.yml`

```
swipe:
  4:
    up:
      command: 'xdotool key super+s'
    down:
      command: 'xdotool key super+a'
    key_leftmeta:
      up:
        command: 'xdotool key XF86MonBrightnessUp'
      down:
        command: 'xdotool key XF86MonBrightnessDown'
```
