### ISSUE TITLE
Disabling some shortcuts

### ISSUE THREAD

**Issue by EBazarov** [iberianpig/fusuma#14]
I don't want to use some of shortcuts, for example "pinch", after deleting them from config file,fusuma will crashed after some moment.

If I will use config like this :
```
swipe:
  3: 
    left: 
      shortcut: 'super+Left'
    right: 
      shortcut: 'super+Right'
    up: 
      shortcut: ''
    down: 
      shortcut: ''
  4:
    left: 
      shortcut: ''
    right: 
      shortcut: ''
    up: 
      shortcut: 'super+a'
    down: 
      shortcut: 'super+s'
pinch:
  in:
    shortcut: ''
  out:
    shortcut: ''
```

It will print errors in log file, but will be still functional.

```
You specified the wrong number of args.
Usage: key [options] <keysequence> [keysequence ...]
--clearmodifiers     - clear active keyboard modifiers during keystrokes
--delay DELAY        - Use DELAY milliseconds between keystrokes
--repeat TIMES       - How many times to repeat the key sequence
--repeat-delay DELAY - DELAY milliseconds between repetitions
--window WINDOW      - send keystrokes to a specific window
Each keysequence can be any number of modifiers and keys, separated by plus (+)
  For example: alt+r

Any letter or key symbol such as Shift_L, Return, Dollar, a, space are valid,
including those not currently available on your keyboard.

If no window is given, and there are windows in the stack, %1 is used. Otherwise
the currently-focused window is used
This command consumes all arguments after it, so you cannot chain
 additional commands after it.
```

I think one of the way hadle it, check if key filed is empty
