### ISSUE TITLE
Quick swipes are not recognised by Fusuma

### ISSUE THREAD

**Issue by validatedev** [iberianpig/fusuma#147]
**Describe the bug**
For example, cannot swipe back and forth quickly between two workspaces. When I look on libinput-debug-events log, it is recognised by debug but not with fusuma (looked fusuma's log). And adding that I'm using fusuma-plugin-wmctrl, so there isn't any problem with xdotool.

**To Reproduce**
1. Swipe back and forth quickly.
2. You cannot do 'forth' step.

**Expected behavior**
You should swipe seamlessly.

**Versions**
```
I, [2019-12-25T20:56:26.965234 #5138]  INFO -- : reload config : /home/validate/.config/fusuma/config.yml
I, [2019-12-25T20:56:26.965318 #5138]  INFO -- : ---------------------------------------------
I, [2019-12-25T20:56:26.965336 #5138]  INFO -- : Fusuma: 1.3.0
I, [2019-12-25T20:56:26.966836 #5138]  INFO -- : libinput: 1.10.4
I, [2019-12-25T20:56:26.967411 #5138]  INFO -- : OS: Linux 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019
I, [2019-12-25T20:56:26.967888 #5138]  INFO -- : Distribution: Ubuntu 18.04.3 LTS \n \l
I, [2019-12-25T20:56:26.968337 #5138]  INFO -- : Desktop session: ubuntu
I, [2019-12-25T20:56:26.968375 #5138]  INFO -- : ---------------------------------------------
I, [2019-12-25T20:56:26.968392 #5138]  INFO -- : ---------------------------------------------
I, [2019-12-25T20:56:26.968404 #5138]  INFO -- : Enabled Plugins: 
I, [2019-12-25T20:56:26.968454 #5138]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2019-12-25T20:56:26.968468 #5138]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2019-12-25T20:56:26.968481 #5138]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2019-12-25T20:56:26.968492 #5138]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2019-12-25T20:56:26.968503 #5138]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2019-12-25T20:56:26.968514 #5138]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2019-12-25T20:56:26.968524 #5138]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2019-12-25T20:56:26.968555 #5138]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2019-12-25T20:56:26.968566 #5138]  INFO -- :   Fusuma::Plugin::Executors::WmctrlExecutor
I, [2019-12-25T20:56:26.968575 #5138]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2019-12-25T20:56:26.968605 #5138]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2019-12-25T20:56:26.968613 #5138]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2019-12-25T20:56:26.968620 #5138]  INFO -- : ---------------------------------------------
```

Kernel version: `5.0.0-23-generic #24~18.04.1-Ubuntu`
OS: Ubuntu 18.04.3

```
swipe:
  3:
    left:
      command: 'xdotool key alt+Right'
      threshold: 0.5
    right:
      command: 'xdotool key alt+Left'
      threshold: 0.5
    up:
      workspace: 'next'
      threshold: 0.5
    down:
      workspace: 'prev'
      threshold: 0.5
  4:
    up:
      workspace: 'next'
      threshold: 0.5
    down:
      workspace: 'prev'
      threshold: 0.5
pinch:
  2:
    in:
      command: 'xdotool keydown ctrl click 4 keyup ctrl'
      threshold: 0.5
    out:
      command: 'xdotool keydown ctrl click 5 keyup ctrl'
      threshold: 0.5

threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1
```
