### ISSUE TITLE
Some gestures do not work anymore after resume

### ISSUE THREAD

**Issue by marcociara379** [iberianpig/fusuma#148]
Hello,
I am experimenting with Fusuma, and it seems to work fine on my machine, a Dell XPS 15-9530 with Ubuntu 18.04 with kernel `4.15.0-72-generic`. Fusuma version: `1.3.0`. Libinput version `1.10.4`
It works flawlessly until I suspend the system and resume it. At this point, the three finger swipe do not work as reliably anymore: sometimes the up/down swipes are recognized as scrolls and the 3 fingers right/left swipe does nothing.

Any hint?

my `~/.config/fusuma/config.yml` looks like the following:

```yaml
swipe:
  3:
    left:
      command: 'xdotool key alt+Shift+Tab'
    right:
      command: 'xdotool key alt+Tab'
    up:
      command: 'xdotool key super+s'
    down:
      command: 'xdotool key super+s'
  4:
    up:
      command: 'xdotool key ctrl+alt+Down'
    down:
      command: 'xdotool key ctrl+alt+Up'
pinch:
  in:
    command: 'xdotool key ctrl+plus'
    threshold: 0.1
  out:
     command: 'xdotool key ctrl+minus'
     threshold: 0.1

threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1
```
