### ISSUE TITLE
2 finger swipe

### ISSUE THREAD

**Issue by Sandvich** [iberianpig/fusuma#155]
**Is your feature request related to a problem? Please describe.**
Hi! I've been loving Fusuma so far, but the one thing I'm really missing is two-finger swipes to go back and forwards a page, like on MacOS. Is this something that's possible?

I've already put it in my config, but sadly it doesn't seem to recognise the gesture. I have it mapped to alt+Left/alt+Right, which is already a thing in KDE

**Additional context**
Just in case this is already enabled and I've just made a mistake, here's my config:
```yaml
swipe:
  2:
    left:
      command: 'xdotool key alt+Left'
    right:
      command: 'xdotool key alt+Right'
  3:
    left:
      workspace: 'next'
    right:
      workspace: 'prev'
    up:
      command: 'xdotool key Control_L+F10'
pinch:
  2:
    in:
      command: 'xdotool keydown ctrl click 4 keyup ctrl' # Zoom in
    out:
      command: 'xdotool keydown ctrl click 5 keyup ctrl' # Zoom out

threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1
```
