### ISSUE TITLE
Auto generating ~/.config.yml from boilerplate

### ISSUE THREAD

**Issue by iberianpig** [iberianpig/fusuma#166]
**Is your feature request related to a problem? Please describe.**

The built-in config.yml works as a fallback, so users can't notice that ~/.config.yml is not configured correctly.
The user thinks he's set it up correctly, but it's executing a different command. It's a bug! (Actually, the problem is that config.yml is not set to the correct path)

**Describe the solution you'd like**
* Stop the built-in config.yml and default gestures
* Generate ~/.config.yml from boilerplate(ubuntu/elementaryOS/...)

**Describe alternatives you've considered**

* It may be easier to understand if you display the following in your built-in config.yml.
```yml

swipe:
  3:
    left:
      command: echo ”swipe →3 fingers → left. you can configure $XDG_CONFIG/fusuma/config.yml”

```
