### ISSUE TITLE
Multi finger tab word lookup

### ISSUE THREAD

**Issue by volfgox** [iberianpig/fusuma#168]
I want to enable looking up a word for instance in a we page by 3 fingers tap over it in Ubuntu. Is this possible with fusuma (or maybe with additional fusuma plugins)?

**Comment by iberianpig** [comment]
I think you can do that.
Try [fusuma-plugin-tap](https://github.com/iberianpig/fusuma-plugin-tap).

You need to make a script that copies the word you are highlighting and runs it as an argument in your browser or dictionary.

**Comment by iberianpig** [comment]
volfgox Please install `xsel` and `fusuma-plugin-tap` and try following

```yaml
tap:
  3:
    command: 'xdg-open https://www.google.com/search?q="$(xsel -p)"'
```

**Comment by volfgox** [comment]
Thank you. This helps a lot.
Furthermore, it would be great if the word is selected before opening the URL. Currently, I should select the word with a tap-2 and then a tap-3 to lookup. Merging both of these operations into just the tap-3 will be wonderful. Any idea?

**Comment by iberianpig** [comment]
I think that it would be nice to have a chrome extension that search word under the cursor.

**Comment by volfgox** [comment]
It would be nicer if this feature could be available everywhere not just in a browser. Just like in Mac OS.
The only missing feature to achieve this is highlighting the word under cursor with tap-3. What do you think? Is it possible this with fusuma? If not, is it possible to add the feature? I can contribute to add new features.

**Comment by iberianpig** [comment]
You may need a small dictionary app that pops up at the cursor position.

I think it would be difficult to implement the ability to make fusuma highlight characters.
Instead, it seems easy to run two commands in a row: "double-click to select a character" and "search for the selected character".

**Comment by volfgox** [comment]
Thank you very much. I finally come up with a solution that works properly for me:
```yaml
tap:
  3:
    command: 'xdotool click --repeat 2 1 && xdg-open https://www.google.com/search?q="$(xsel -p)"'
```
