### ISSUE TITLE
Unable to reprogram Pinch 

### ISSUE THREAD

**Issue by fookitt** [iberianpig/fusuma#171]
**Describe the bug**
Loaded config.yml with PopOS Default Gnome config. Tried to reprogram pinch in and out, but it is 'stuck' to commands Ctrl+Super+Up' (pinch in, move to workspace up) and Ctrl+Super+Down' (pinch out, move to workspace down). I currently have no config for pinch actions and yet it is still 'stuck' to those commands.

I have reloaded Fusuma by running Fusuma with -d. 
I have log off and log back on, and yet the pinch actions are 'stuck' to those shortcut.
I am able to reprogram other gestures. 

Running the command fusuma to list actions/commands, I am able to see other gestures but not pinch (currently set to nothing) and yet it activates the command to move up/down to other workspace.

**Versions**
Fusuma: 1.10.0
libinput: 1.15.5
Linux 5.4.0-7626-generic #30~1588169883~20.04~bbe668a-Ubuntu SMP Wed Apr  Pop!_OS 20.04 LTS \n \l
Desktop session: pop x11

**Additional context**
```
swipe:
  4:
    up:
      command: 'xdotool key Ctrl+Super+Down'
    down:
      command: 'xdotool key Ctrl+Super+Up'
    left:
      command: 'xdotool key Ctrl+Super+Left'
    right:
      command: 'xdotool key Ctrl+Super+Right'

  3:
    up:
      command: 'xdotool key Super+s'
    down:
      command: 'xdotool key Super+d'
    left:
      command: 'xdotool key Alt+Right'
    right:
      command: 'xdotool key Alt+Left'


threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1

```
