### ISSUE TITLE
Window Prev/Next moves desktop environment when no active window

### ISSUE THREAD

**Issue by Japnix** [iberianpig/fusuma#178]
OS: Ubuntu 20.04
Desktop Environment: KDE

```
  4:
    left:
      workspace: 'next' # Switch to next workspace
      keypress:
        LEFTSHIFT:
          window: 'next' # Move window to next workspace
        LEFTALT:
          command: 'xdotool key --clearmodifiers super+Left' # Move window to left side
    right:
      workspace: 'prev' # Switch to previous workspace
      keypress:
        LEFTSHIFT:
          window: 'prev' # Move window to previous workspace
        LEFTALT:
          command: 'xdotool key --clearmodifiers super+Right'  # Move window to right side
```
I'm running into an issue with:

`window: 'prev' # Move window to previous workspace`

If there is an active window or application running it moves the applications between the workspace without an issue.  However, if do this gesture with no active applications in a workspace, it seems to move the Desktop Environment components between each work space (Wallpaper, Ability to right click desktop to get options).

Looking for a way to prevent the gesture from moving desktop components
