### ISSUE TITLE
Problem with shortcut and AZERTY ?

### ISSUE THREAD

**Issue by PrestanceDesign** [iberianpig/fusuma#18]
Hi !

All shorcuts of my configuration work except up (`super+w`).
```yml
swipe:
  3:
    left:
      shortcut: 'ctrl+alt+l'
    right:
      shortcut: 'ctrl+alt+h'
    up:
      shortcut: 'super+w'
    down:
      shortcut: 'super+s'
```

On my Ubuntu 16.10 (Unity), I use `super+w` for expose windows, but with Fusuma is act like `super+z`.
Do you have an idea ? Maybe my keyboard layout is AZERTY ?
