### ISSUE TITLE
Pinch in gesture not recognized in Popos 20.04 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by john-ghatas** [iberianpig/fusuma#184]
**Describe the bug**
Pinch in gesture is not recognized

**To Reproduce**
1. Run fusuma command in the terminal 
```bash
fusuma
```
2. Pinch out, it shows up in the debugger
3. Pinch in, it doesn't show up in the debugger

**Expected behavior**
Pinching out works as expected, pinching in does not

**Versions**
You can get this information from copy and paste the output of `fusuma --version` from the command line. Also, please include the OS and what version of the OS you're running.
![image](https://user-images.githubusercontent.com/14125058/84715529-ff247a00-af70-11ea-9e71-bc602c894c61.png)

**Additional context**
Any additional context, your `~/.config/fusuma/config.yml` or data that might be necessary to reproduce the issue.
The current setup looks like this
```yaml
swipe:
  3:
    left:
      command: "xdotool key alt+Right" # History forward 
    right:
      command: "xdotool key alt+Left" # History back
    up:
      command: "xdotool key ctrl+Super+Down" # Switch to next workspace
    down:
      command: "xdotool key ctrl+Super+Up" # Switch to previous workspace

  4:
    up:
      command: "xdotool key super" # Activity
    down:
      command: "xdotool key super" # Activity
    
pinch:
  2: 
    in:
      command: "xdotool keydown ctrl click 4 && xdotool keyup ctrl" # threshold: 0.5, interval: 0.5
  2: 
    out:
      command: "xdotool keydown ctrl click 5 keyup ctrl" # threshold: 0.5, interval: 0.5

threshold:
  pinch: 0.5

interval:
  swipe: 0.75
  pinch: 0.5
```
