### ISSUE TITLE
Ctrl zoom

### ISSUE THREAD

**Issue by pronaww** [iberianpig/fusuma#186]
**Describe the bug**
Software which support CTRL+scroll to zoom in/out have this problem. Opening Workspace presses Ctrl button by xdotool and touch pad scroll happening automatically because of making the gesture.

In firefox, I disabled mousewheel.with_control.action in about::config from 3(zoom) to 1(scroll). But Nemo file manager doesn't have this option of disable CTRL zoom.

If you can provide a procedure to disable CTRL zoom system wide, that will be very helpful.

**Expected behavior**

**Versions**

```
I, [2020-06-23T18:02:08.313514 #19450]  INFO -- : ---------------------------------------------
I, [2020-06-23T18:02:08.313558 #19450]  INFO -- : Fusuma: 1.10.1
I, [2020-06-23T18:02:08.315018 #19450]  INFO -- : libinput: 1.10.4
I, [2020-06-23T18:02:08.315580 #19450]  INFO -- : OS: Linux 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020
I, [2020-06-23T18:02:08.316134 #19450]  INFO -- : Distribution: Linux Mint 19.3 Tricia \n \l
I, [2020-06-23T18:02:08.316712 #19450]  INFO -- : Desktop session: cinnamon x11
I, [2020-06-23T18:02:08.316738 #19450]  INFO -- : ---------------------------------------------
I, [2020-06-23T18:02:08.316759 #19450]  INFO -- : Enabled Plugins: 
I, [2020-06-23T18:02:08.316822 #19450]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2020-06-23T18:02:08.316839 #19450]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2020-06-23T18:02:08.316856 #19450]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2020-06-23T18:02:08.316875 #19450]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2020-06-23T18:02:08.316894 #19450]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2020-06-23T18:02:08.316913 #19450]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2020-06-23T18:02:08.316933 #19450]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2020-06-23T18:02:08.316951 #19450]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2020-06-23T18:02:08.316971 #19450]  INFO -- :   Fusuma::Plugin::Executors::WmctrlExecutor
I, [2020-06-23T18:02:08.316990 #19450]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2020-06-23T18:02:08.317010 #19450]  INFO -- :   Fusuma::Plugin::Filters::LibinputTimeoutFilter
I, [2020-06-23T18:02:08.317028 #19450]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2020-06-23T18:02:08.317047 #19450]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2020-06-23T18:02:08.317066 #19450]  INFO -- : ---------------------------------------------
```

**Additional context**
```
swipe:
  3: 
    left: 
      command: 'xdotool key alt+Right'
    right: 
      command: 'xdotool key alt+Left'
    up: 
      command: 'xdotool key super'
    down: 
      command: 'xdotool key super'
  4:
    left: 
      command: 'xdotool key ctrl+alt+Down'
    right: 
      command: 'xdotool key ctrl+alt+Up'
    up: 
      command: 'xdotool key ctrl+alt+Down'
    down: 
      command: 'xdotool key ctrl+alt+Up'
pinch:
  in:
    command: 'xdotool keydown ctrl key plus keyup ctrl'
  out:
    command: 'xdotool keydown ctrl key minus keyup ctrl'
```
