### ISSUE TITLE
"ERROR -- : unknown keyword: filename" thrown after upgrading from 1.10.1 to 1.11.0

### ISSUE THREAD

**Issue by kats86** [iberianpig/fusuma#194]
hi,
first of all, thanks for the _great work_ so far :+1:. however, I stumpled upon the following error after upgrading to **fusuma_1.11.0**:
```
I, [2020-07-26T23:28:59.143073 #9193]  INFO -- : reload config: /home/kay/.config/fusuma/config.yml
E, [2020-07-26T23:28:59.143162 #9193] ERROR -- : unknown keyword: filename
Traceback (most recent call last):
	10: from /usr/local/bin/fusuma:23:in `<main>'
	 9: from /usr/local/bin/fusuma:23:in `load'
	 8: from /var/lib/gems/2.5.0/gems/fusuma-1.11.0/exe/fusuma:41:in `<top (required)>'
	 7: from /var/lib/gems/2.5.0/gems/fusuma-1.11.0/lib/fusuma.rb:17:in `run'
	 6: from /var/lib/gems/2.5.0/gems/fusuma-1.11.0/lib/fusuma.rb:32:in `read_options'
	 5: from /var/lib/gems/2.5.0/gems/fusuma-1.11.0/lib/fusuma.rb:51:in `load_custom_config'
	 4: from /var/lib/gems/2.5.0/gems/fusuma-1.11.0/lib/fusuma/config.rb:24:in `custom_path='
	 3: from /var/lib/gems/2.5.0/gems/fusuma-1.11.0/lib/fusuma/config.rb:39:in `custom_path='
	 2: from /var/lib/gems/2.5.0/gems/fusuma-1.11.0/lib/fusuma/config.rb:46:in `reload'
	 1: from /var/lib/gems/2.5.0/gems/fusuma-1.11.0/lib/fusuma/config.rb:52:in `validate'
/var/lib/gems/2.5.0/gems/fusuma-1.11.0/lib/fusuma/config.rb:67:in `rescue in validate': unknown keyword: filename (Fusuma::Config::InvalidFileError)
```
**fusuma_1.10.1** works fine (config.yml unchanged):
```
I, [2020-07-26T23:51:11.839560 #3350]  INFO -- : ---------------------------------------------
I, [2020-07-26T23:51:11.839608 #3350]  INFO -- : Fusuma: 1.10.1
I, [2020-07-26T23:51:11.841559 #3350]  INFO -- : libinput: 1.10.4
I, [2020-07-26T23:51:11.842358 #3350]  INFO -- : OS: Linux 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020
I, [2020-07-26T23:51:11.843227 #3350]  INFO -- : Distribution: elementary OS Hera \n \l
I, [2020-07-26T23:51:11.844010 #3350]  INFO -- : Desktop session: pantheon x11
I, [2020-07-26T23:51:11.844040 #3350]  INFO -- : ---------------------------------------------
I, [2020-07-26T23:51:11.844056 #3350]  INFO -- : Enabled Plugins: 
I, [2020-07-26T23:51:11.844119 #3350]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2020-07-26T23:51:11.844139 #3350]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2020-07-26T23:51:11.844150 #3350]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2020-07-26T23:51:11.844161 #3350]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2020-07-26T23:51:11.844171 #3350]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2020-07-26T23:51:11.844187 #3350]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2020-07-26T23:51:11.844208 #3350]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2020-07-26T23:51:11.844221 #3350]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2020-07-26T23:51:11.844233 #3350]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2020-07-26T23:51:11.844244 #3350]  INFO -- :   Fusuma::Plugin::Filters::LibinputTimeoutFilter
I, [2020-07-26T23:51:11.844255 #3350]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2020-07-26T23:51:11.844279 #3350]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2020-07-26T23:51:11.844296 #3350]  INFO -- : ---------------------------------------------
I, [2020-07-26T23:51:11.844869 #3350]  INFO -- : reload config : /home/kay/.config/fusuma/config.yml
```
my **config.yml** (nothing special I suppose):
```
swipe:
  3:
    left:
      command: 'xdotool key ctrl+alt+Right'
    right:
      command: 'xdotool key ctrl+alt+Left'
    up:
      command: 'xdotool key super+s'
    #down:
    #  command: 'xdotool key super+s'
  4:
    left:
      command: 'xdotool key super+alt+Right'
    right:
      command: 'xdotool key super+alt+Left'
    #up:
      #command: 'xdotool key super+a'
    #down:
      #command: 'xdotool key super+s'

pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
    command: 'xdotool key ctrl+minus'

threshold:
  swipe: 1
  pinch: 0.5

interval:
  swipe: 1
  pinch: 0.5
```
rolling back to fusuma_1.10.1 resolves the issue completely. _take care & stay save!_
