### ISSUE TITLE
Fusuma wont work after resuming from suspend on wayland

### ISSUE THREAD

**Issue by HritwikSinghal** [iberianpig/fusuma#208]
**Describe the bug**
fusuma wont recognize gestures after waking up from suspend state on ubuntu 20.04.1 Wayland. It works fine on Xorg.

**To Reproduce**
1.Install fusuma (as mentioned in guide) with its plugins (sendkey and tap), and i configure my yml (given below).
2. add 'fusuma -d' or 'path/to/fusuma -d' in startup apps and all is working correctly. It is working across restarts and has expected behavior on gestures.
3. On wayland, click on suspend and after waking up from suspend, the gestures wont work. Fusuma service is running ("ps -ef | grep fusuma" shows fusuma running). If i start it again ("fusuma -d"),  it starts and works fine. 
Now note also that after starting the fusuma after waking up from suspend (i.e after step 3) it persists across suspends, meaning i have to start fusuma only after first suspend and it will function correctly after every suspend from now until i reboot.

**Expected  behavior**
fusuma should work after suspend without running it again

**Versions**
You can get this information from copy and paste the output of `fusuma --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
I, [2020-10-16T21:09:56.541010 #24990]  INFO -- : reload config: /home/hritwik/.config/fusuma/config.yml
I, [2020-10-16T21:09:56.593344 #24990]  INFO -- : ---------------------------------------------
I, [2020-10-16T21:09:56.593377 #24990]  INFO -- : Fusuma: 1.11.1
I, [2020-10-16T21:09:56.594721 #24990]  INFO -- : libinput: 1.15.5
I, [2020-10-16T21:09:56.595227 #24990]  INFO -- : OS: Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020
I, [2020-10-16T21:09:56.595685 #24990]  INFO -- : Distribution: Ubuntu 20.04.1 LTS \n \l
I, [2020-10-16T21:09:56.596137 #24990]  INFO -- : Desktop session: ubuntu-wayland wayland
I, [2020-10-16T21:09:56.596153 #24990]  INFO -- : ---------------------------------------------
I, [2020-10-16T21:09:56.596162 #24990]  INFO -- : Enabled Plugins: 
I, [2020-10-16T21:09:56.596231 #24990]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2020-10-16T21:09:56.596243 #24990]  INFO -- :   Fusuma::Plugin::Buffers::KeypressBuffer
I, [2020-10-16T21:09:56.596251 #24990]  INFO -- :   Fusuma::Plugin::Buffers::TapBuffer
I, [2020-10-16T21:09:56.596258 #24990]  INFO -- :   Fusuma::Plugin::Detectors::KeypressDetector
I, [2020-10-16T21:09:56.596265 #24990]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2020-10-16T21:09:56.596272 #24990]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2020-10-16T21:09:56.596279 #24990]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2020-10-16T21:09:56.596287 #24990]  INFO -- :   Fusuma::Plugin::Detectors::TapDetector
I, [2020-10-16T21:09:56.596295 #24990]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2020-10-16T21:09:56.596304 #24990]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2020-10-16T21:09:56.596311 #24990]  INFO -- :   Fusuma::Plugin::Events::Records::KeypressRecord
I, [2020-10-16T21:09:56.596318 #24990]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2020-10-16T21:09:56.596325 #24990]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2020-10-16T21:09:56.596333 #24990]  INFO -- :   Fusuma::Plugin::Executors::SendkeyExecutor
I, [2020-10-16T21:09:56.596343 #24990]  INFO -- :   Fusuma::Plugin::Filters::KeypressFilter
I, [2020-10-16T21:09:56.596351 #24990]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2020-10-16T21:09:56.596359 #24990]  INFO -- :   Fusuma::Plugin::Filters::LibinputTimeoutFilter
I, [2020-10-16T21:09:56.596367 #24990]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2020-10-16T21:09:56.596375 #24990]  INFO -- :   Fusuma::Plugin::Parsers::KeypressParser
I, [2020-10-16T21:09:56.596385 #24990]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2020-10-16T21:09:56.596394 #24990]  INFO -- :   Fusuma::Plugin::Parsers::TapParser
I, [2020-10-16T21:09:56.596402 #24990]  INFO -- : ---------------------------------------------

```

Ubuntu 20.04.1 Walyand.

**Additional context**
Any additional context, your `~/.config/fusuma/config.yml` or data that might be necessary to reproduce the issue.

```
swipe:
  3:
    left:
      # sendkey: "LEFTALT+RIGHT" # history back
      keypress:
        LEFTCTRL:
          sendkey: "PREVIOUSSONG"
        # LEFTMETA+LEFTALT:
          # sendkey: 'BRIGHTNESSDOWN'

    right:
      # sendkey: "LEFTALT+LEFT" # history forward
      keypress:
        LEFTCTRL:
          sendkey: "NEXTSONG"
        # LEFTMETA+LEFTALT:
        #   sendkey: 'xdotool key --clearmodifiers XF86AudioLowerVolume'

    up:
      sendkey: "LEFTMETA" # Overview
      keypress:
        LEFTCTRL:
          sendkey: "LEFTCTRL+K" # open new tab
        LEFTCTRL+LEFTALT:
          sendkey: 'BRIGHTNESSUP'

    down:
      sendkey: "LEFTMETA" # Overview
      keypress:
        LEFTCTRL:
          sendkey: "LEFTCTRL+COMMA" # close tab
        LEFTCTRL+LEFTALT:
          sendkey: 'BRIGHTNESSDOWN'

  4:
    left:
      sendkey: "VOLUMEDOWN"
    right:
      sendkey: "VOLUMEUP"
#     up:
#       sendkey: "xdotool key ctrl+alt+Down" # Switch to next workspace
#     down:
#       sendkey: "xdotool key ctrl+alt+Up" # Switch to previous workspace
pinch:
  in:
    sendkey: "ZOOMOUT" # Zoom in
  out:
    sendkey: "ZOOMIN" # Zoom out


threshold:
  pinch: 0.4
  swipe: 0.2

interval:
  swipe: 0.8
  pinch: 0.5
  tap: 0.2

tap:
  # 1:
  #   sendkey: "echo ----------------tap1----------------------------"
  # 2:
  #   sendkey: "echo ----------------tap2----------------------------"
  # 3:
  #   sendkey: "echo ----------------tap3----------------------------"
  # 4:
    # sendkey: "PLAYPAUSE"

hold:
#   1:
#     command: "echo ----------------hold1----------------------------"
#   2:
#     command: "echo ----------------hold2----------------------------"
#   3:
#     command: "echo ----------------hold3----------------------------"
  4:
    sendkey: "PLAYPAUSE"

plugin: 
  inputs:
    libinput_command_input:
      enable-tap: true
      verbose: true
      show-keycodes: true

```

Note that this issue happens on my dell laptop which completely suspends and not on my lenovo laptop which doesn't completely suspend (i can tell that since on my dell laptop fans stop working but on lenovo, they dont) (and i am not talking about hibernate here). I have also setup ubuntu without swap partition so ubuntu itself handles swap (currently 2GB), this maybe of help.
