### ISSUE TITLE
Natural Scrolling

### ISSUE THREAD

**Issue by GeorgiosNikas** [iberianpig/fusuma#21]
Hi im using Ubuntu 16.10 with Gnome 3.20 and its working fine, but the scrolling direction is inverted. Under Settings the Option for Natural Scrolling disappeared. How do I enable it?

**Comment by iberianpig** [comment]
If you want to set scroll direction as inverted, you should try to set your config file.
You can customize the settings for gestures to put and edit ~/.config/fusuma/config.yml.

**Comment by GeorgiosNikas** [comment]
The problem is that i dont have the Fusuma folder in .config, I searched everywhere for it but I cant find it.

**Comment by iberianpig** [comment]
Please try create fusuma directory in `~/.config` and put config.yml in fusuma directory.

**Comment by GeorgiosNikas** [comment]
And what should I write into the file?

**Comment by Saboteur777** [comment]
@GeorgiosNikas I did the following: 

1. enabled the natural scroll in Mouse and Keyboards > Natural scrolling 
2. then created ~/.config/fusuma folder
3. created config.yml, with the following content: 

```
swipe:
  3: 
    left: 
      shortcut: 'alt+Right'
    right: 
      shortcut: 'alt+Left'
    #up: 
    #  shortcut: ''
    down: 
      shortcut: 'ctrl+r'
  4:
    left: 
      shortcut: 'ctrl+alt+Right'
    right: 
      shortcut: 'ctrl+alt+Left'
    up: 
      shortcut: 'ctrl+alt+Down'
    down: 
      shortcut: 'ctrl+alt+Up'

threshold:
  swipe: 0.15
  pinch: 0

```

You can customise it as you wish from now. **Note:** I disabled pinch-to-zoom. Lines starting with _#_ are commented out.
