### ISSUE TITLE
Executing any three finger gesture it still gets passed on to the application

### ISSUE THREAD

**Issue by zakhar-bykov** [iberianpig/fusuma#211]
**Describe the bug**
When executing any three finger gesture it still gets passed on to the application.
Example: When I scroll in Google Chrome on a webpage or any application with scrolling views with three fingers up / down (fusuma simulates pressing a super key and shows me all open apps in that workspace) or scrolls left / right (fusuma emulates switching tab / shift tab) the gesture does not start and fusuma doesn't show it in the console (not in --daemon mode). Sometimes it works, sometimes it doesn't.

**To Reproduce**
1. Open any site in Google Chrome
2. Scrolling with three fingers in any direction

**Expected behavior**
Three-fingers scrolling up / down - show all open apps in this workspace (press super key).
Three-fingers scrolling left / right - switching between tabs in browser (press tab / shift tab).

**Versions**
It hapends on versions 1.9.? and 1.11.1. Don't know about this issue on another versions.
```
I, [2020-11-23T16:15:24.246493 #28888]  INFO -- : reload config: /home/zakhar/.config/fusuma/config.yml
I, [2020-11-23T16:15:24.281383 #28888]  INFO -- : ---------------------------------------------
I, [2020-11-23T16:15:24.281424 #28888]  INFO -- : Fusuma: 1.11.1
I, [2020-11-23T16:15:24.283430 #28888]  INFO -- : libinput: 1.10.4
I, [2020-11-23T16:15:24.284288 #28888]  INFO -- : OS: Linux 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020
I, [2020-11-23T16:15:24.285069 #28888]  INFO -- : Distribution: Ubuntu 18.04.5 LTS \n \l
I, [2020-11-23T16:15:24.285794 #28888]  INFO -- : Desktop session: ubuntu x11
I, [2020-11-23T16:15:24.285826 #28888]  INFO -- : ---------------------------------------------
I, [2020-11-23T16:15:24.285854 #28888]  INFO -- : Enabled Plugins:
I, [2020-11-23T16:15:24.285941 #28888]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2020-11-23T16:15:24.285958 #28888]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2020-11-23T16:15:24.285969 #28888]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2020-11-23T16:15:24.285980 #28888]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2020-11-23T16:15:24.285992 #28888]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2020-11-23T16:15:24.286003 #28888]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2020-11-23T16:15:24.286014 #28888]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2020-11-23T16:15:24.286024 #28888]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2020-11-23T16:15:24.286035 #28888]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2020-11-23T16:15:24.286046 #28888]  INFO -- :   Fusuma::Plugin::Filters::LibinputTimeoutFilter
I, [2020-11-23T16:15:24.286057 #28888]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2020-11-23T16:15:24.286229 #28888]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2020-11-23T16:15:24.286244 #28888]  INFO -- : ---------------------------------------------
```

**Additional context**
My config.yml file:
```
swipe:
  3:
    left:
      command: 'xte "keydown Control_L" "key Tab" "keyup Control_L"'
      threshold: 0.8
      interval: 0.4
    right:
      command: 'xte "keydown Control_L" "keydown Shift_L" "key Tab" "keyup Shift_L" "keyup Control_L"'
      threshold: 0.8
      interval: 0.4
    up:
      command: 'xte "key Super_L"'
      threshold: 0.6
      interval: 1
    down:
      command: 'xte "key Super_L"'
      threshold: 0.6
      interval: 1
  4:
    left:
      command: 'xte "keydown Alt_L" "key Right" "keyup Alt_L"'
      threshold: 1
      interval: 0.3
    right:
      command: 'xte "keydown Alt_L" "key Left" "keyup Alt_L"'
      threshold: 1
      interval: 0.3
    up:
      command: 'xte "keydown Control_L" "keydown Super_L" "key Down" "keyup Super_L" "keyup Control_L"'
      threshold: 0.6
      interval: 0.8
    down:
      command: xte "keydown Control_L" "keydown Super_L" "key Up" "keyup Super_L" "keyup Control_L"
      threshold: 0.6
      interval: 0.8
pinch:
  2:
    in:
      command: 'xte "keydown Control_L" "key plus" "keyup Control_L"'
    out:
      command: 'xte "keydown Control_L" "key minus" "keyup Control_L"'
#rotate:
#  3:
#    clockwise:
#      command: 'amixer set Master 10+'
#    counterclockwise:
#      command: 'amixer set Master 10-'

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.2
  pinch: 2
```
