### ISSUE TITLE
Three finger gestures unreliable

### ISSUE THREAD

**Issue by marvinmai** [iberianpig/fusuma#212]
Very often, fusuma is not detecting three finger gestures. Some times it's working fine, but around half the time for a certain time it's not working. After some time it starts working again. I tried to observe if it's a certain action that reactivates it, but I wasn't able to figure sth. out. 
This is the content of my config.yml file.
````
swipe:
  3:
    left:
      command: 'xdotool key alt+Right'
    right:
      command: 'xdotool key alt+Left'
    up:
      command: 'xdotool key super'
    down:
      command: 'xdotool key super+a'
  4:
    left:
      command: 'xdotool key ctrl+super+Left'
    right:
      command: 'xdotool key ctrl+super+Right'
    up:
      command: 'xdotool key super+ctrl+Down'
    down:
      command: 'xdotool key super+ctrl+Up'
pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
     command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
````
