### ISSUE TITLE
No fallback to default with modifier keypress

### ISSUE THREAD

**Issue by iberianpig** [iberianpig/fusuma#237]
**Describe the bug**

No fallback to default when keypress: is assigned to begin/update/end of swipe.

**To Reproduce**
The following configuration reproduce the problem

```yaml
swipe:
  3:
    begin:
      command: xdotool mousedown 1
    update:
      command: xdotool mousemove_relative -- $move_x, $move_y
      interval: 0.01
      accel: 2
    end:
      command: xdotool mouseup 1
      keypress:
        LEFTSHIFT+LEFTCTRL: &deepl
          command: xdotool mouseup 1; test -n "$(xsel -p)" && echo $(xsel -p) | ruby -r cgi -ne 'puts CGI.escape $_.chomp' | xargs -I{} google-chrome  --incognito --app=deepl.com https://www.deepl.com/translator#en/ja/{}
          interval: 5
        LEFTCTRL+LEFTSHIFT:
          <<: *deepl

```

- It works: If I drag and drop without holding any key, it works well.
- It works: If I drag and drop while holding `LEFTCTRL+LEFTSHIFT`, translate the selected sentences in deepl.com.
- Not working: If I drag and drop while holding down Super key(`LEFTMETA`), the right mouse button will be kept presse when I release the Super key. (It seems that the mouse button release assigned to default `end:` event is not working).

I think this is not a bug in fusuma-plugin-keypress, but a problem in merging "modifierr records" in `lib/fusuma.rb`.

**Expected behavior**
When drag and drop while holding down Super key,
fusuma triggers the event (swipe/3/end) which releases mouse button.

**Versions**
```yml
I, [2021-05-19T23:41:45.239874 #638190]  INFO -- : reload config: /home/iberianpig/.config/fusuma/config.yml
I, [2021-05-19T23:41:45.311729 #638190]  INFO -- : ---------------------------------------------
I, [2021-05-19T23:41:45.312031 #638190]  INFO -- : Fusuma: 2.0.4
I, [2021-05-19T23:41:45.314638 #638190]  INFO -- : libinput: 1.16.5
I, [2021-05-19T23:41:45.314692 #638190]  INFO -- : ruby 2.7.2p137
I, [2021-05-19T23:41:45.315616 #638190]  INFO -- : OS: Linux 5.6.0-1056-oem #60-Ubuntu SMP Tue May 4 06:40:10 UTC 2021
I, [2021-05-19T23:41:45.316742 #638190]  INFO -- : Distribution: Ubuntu 20.04.2 LTS \n \l
I, [2021-05-19T23:41:45.317543 #638190]  INFO -- : Desktop session: ubuntu x11
I, [2021-05-19T23:41:45.317593 #638190]  INFO -- : ---------------------------------------------
I, [2021-05-19T23:41:45.317619 #638190]  INFO -- : Enabled Plugins:
I, [2021-05-19T23:41:45.317804 #638190]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2021-05-19T23:41:45.317824 #638190]  INFO -- :   Fusuma::Plugin::Buffers::TimerBuffer
I, [2021-05-19T23:41:45.317841 #638190]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2021-05-19T23:41:45.317855 #638190]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2021-05-19T23:41:45.317869 #638190]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2021-05-19T23:41:45.317890 #638190]  INFO -- :   Fusuma::Plugin::Events::Records::ContextRecord
I, [2021-05-19T23:41:45.317904 #638190]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2021-05-19T23:41:45.317917 #638190]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2021-05-19T23:41:45.317935 #638190]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2021-05-19T23:41:45.317956 #638190]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2021-05-19T23:41:45.317980 #638190]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2021-05-19T23:41:45.318000 #638190]  INFO -- :   Fusuma::Plugin::Filters::LibinputTimeoutFilter
I, [2021-05-19T23:41:45.318019 #638190]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2021-05-19T23:41:45.318035 #638190]  INFO -- :   Fusuma::Plugin::Inputs::TimerInput
I, [2021-05-19T23:41:45.318047 #638190]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2021-05-19T23:41:45.318060 #638190]  INFO -- : ---------------------------------------------
```
