### ISSUE TITLE
Suggestion: Allow independent interval value in keypress gestures

### ISSUE THREAD

**Issue by rickardcarlsson** [iberianpig/fusuma#240]
**Is your feature request related to a problem? Please describe.**
Currently you can't use separate interval values for keypress gestures.

Higher level interval affects keypress gesture, keypress interval has no effect:
```
swipe:
  4:
    left:
      update:
        command: 'xdotool key XF86AudioLowerVolume'
        interval: 0.1 # This affects both gestures
        keypress:
          LEFTSHIFT:
            command: 'change_brightness dec'
            interval: 1 # This has no effect
```
**Describe the solution you'd like**
Allow independent interval value in keypress gestures.

**Describe alternatives you've considered**
Changing the invoked scripts, but that interferes with other ways of invoking them.

**Additional context**
```
Fusuma: 2.0.5
libinput: 1.18.0
ruby 3.0.1p64
OS: Linux 5.12.9-1-MANJARO #1 SMP PREEMPT Thu Jun 3 14:56:42 UTC 2021
Distribution: Manjaro Linux \r  (\n) (\l)
Desktop session: plasma x11
```
