### ISSUE TITLE
Can't detect gesture while using keyboard

### ISSUE THREAD

**Issue by DedSecer** [iberianpig/fusuma#247]
I find thay fusuma can't detect gesture while using keyboard, is there a option to enable gesture while using keyboard?

**Comment by iberianpig** [comment]
Have you tried fusuma-plugin-keypress ?

Fusuma can detect gestures while pressing keys.
I think that keys you pressed and keys fusuma sent are mixed.
Maybe the OS doesn't recognize it as a shortcut key because some keys are being sent at the same time?

**Comment by DedSecer** [comment]
Here is my config.yml
```
pinch:
  2:
    in:
      command: 'xdotool key ctrl+equal'
      # command: 'xdotool click 4'
      # sendkey: 'KP4'
    out:
      command: 'xdotool key ctrl+minus'
      # command: 'xdotool click 5'
      # sendkey: 'KP5'
  4:
    in:
      command: 'xdotool key super+a'
    out:
      command: 'xdotool key super+s'
```
My Operating System: Arch Linux
My Desktop: KDE


While I am typing and tyring to pinch in the web browser, I can't not zoom in or zoom out the page. I have installed the fusuma-plugin-keypress but it still doesn't work.

**Comment by iberianpig** [comment]
> My Desktop: KDE

Which are you using Wayland or X11?

If using Wayland, could you try following config?

```yaml
pinch:
  2:
    in:
      sendkey: 'LEFTCTRL+EQUAL'
      threshold: 0.1
    out:
      sendkey: 'LEFTCTRL+MINUS'
      threshold: 0.1

```
