### ISSUE TITLE
Keypress to move cursor events.

### ISSUE THREAD

**Issue by arumihsnek** [iberianpig/fusuma#251]
Hi!

I don't know if this is a issue or a feature request.

I'm trying to use three fingers to "drag a window" (super+left drag) and pressing LEFTMETA change the "size of the window" (super + right drag). I tried multiples combination of the code, looking others examples of code using presskey and a can't do that. Each code works by itself.

```
swipe:
  3:
    begin:
      command: xdotool keydown super mousedown 1
      keypress:
       LEFTMETA:
        begin:
         command: xdotool keydown super mousedown 2
    update:
      command: xdotool mousemove_relative -- $move_x, $move_y
      interval: 0.01
      accel: 8
    end:
      command: xdotool keyup super mouseup 1
      keypress:
       LEFTMETA:
        command: xdotool keyup super mouseup 2
```

I tried too to combine drag windows and different commands to swipe 3 left, swipe right, etc and don't works too.

I don't know if that is possible, or if I'm doing something wrong, maybe if someone had done successfully can share the code?

Thanks!
