### ISSUE TITLE
how can i use  ydotool replace xdotool

### ISSUE THREAD

**Issue by luyanfeng** [iberianpig/fusuma#282]
like this: 
```yml
pinch:
  2:
    in:
      command: "xdotool keydown ctrl click 4 keyup ctrl" # threshold: 0.5, interval: 0.5
    out:
      command: "xdotool keydown ctrl click 5 keyup ctrl" # threshold: 0.5, interval: 0.5
```
how can i use  ydotool replace xdotool
