### ISSUE TITLE
Can anybody give me  a example for sendkey or ydotool

### ISSUE THREAD

**Issue by luyanfeng** [iberianpig/fusuma#300]
I want use fusuma on  ubuntu 22.04  wayland, but only xdotool can work on X11.

I try to use sendkey on X11 but not work... 

I try to use ydotool ,but I won't...

who can help me , thanks very much!

```yaml

pinch:
  2:
    in:
      command: "xdotool keydown ctrl click 4 keyup ctrl" 
        #command: "ydotool key 29:1 12:1 12:0 29:0"
      #sendkey: "LEFTCTRL+MINUS"
      threshold: 0.5
      interval: 0.5
    out:
      command: "xdotool keydown ctrl click 5 keyup ctrl" 
        #command: "ydotool key 29:1 13:1 13:0 29:0"
      #sendkey: "LEFTCTRL+EQUAL"
      threshold: 0.5
      interval: 0.5
  4:
    in:
      command: 'xdotool key super'
      #command: 'ydotool key 29:1 11:1 11:0 29:0'
      threshold: 0.1 
      interval: 10
    out:
      command: 'xdotool key super+a'
      #command: 'ydotool key 29:1 11:1 11:0 29:0'
      threshold: 0.1
      interval: 10

```
