### ISSUE TITLE
Can you add a new parameter to let me execute each gesture only once

### ISSUE THREAD

**Issue by luyanfeng** [iberianpig/fusuma#307]
Can you add a new parameter to let me execute each gesture only once e. g: 

For example, this gesture is used to close a app window：
(I just want to trigger this only once every time I execute this gesture)
```yaml
pinch:
  3:
    out: 
      sendkey: "LEFTALT+F4"  
      threshold: 0.5
      interval: 0.5
      times: 1  # new parameter : this gesture triggers only once.
```
But now, it sometimes closes multiple overlapping windows, This is too scary !
