### ISSUE TITLE
Default values for fuguma

### ISSUE THREAD

**Issue by Shantanu2k19** [iberianpig/fusuma#322]
I have created a configuration file for Fusuma with the following settings:

```yaml
swipe:
  3:
    left:
      command: 'xdotool key alt+Left'  # Back in browser
    right:
      command: 'xdotool key alt+Right' # Forward in browser
```
configuration file at /home/zodiac/.config/fusuma/config.yml, and it is the only configuration file present in that directory.

Despite only defining actions for two gestures (three-finger swipe left and right), Fusuma is also performing actions for other gestures, such as three-finger swipe down and swipe up.

**Question**: Where is Fusuma sourcing commands for these additional gestures? Is there a default configuration file that Fusuma is using for gestures that I haven't explicitly defined?
