### ISSUE TITLE
Volume Controls

### ISSUE THREAD

**Issue by Crims-on** [iberianpig/fusuma#329]
I can't seem to find a way to control the volume with fusuma/xdotool. My keyboard has fn+f6 for volume so I tried both f6 key and function+f6 with fusuma and neither of these did what I wanted. Is there a way to do it already or could it be added?

**Comment by Nukiver** [comment]
So technically this works with Fusuma:
But, you have to swipe multiple times to get your volume up. I couldn't figure out a way to make commands repeat multiple times while I am swiping

```
swipe: 
  3:
    up:
      command: "xdotool key XF86AudioRaiseVolume"
    down:
      command: "xdotool key XF86AudioLowerVolume"

```

**Comment by Nukiver** [comment]
In fact I found something, but it doesn't feel great...

```
swipe: 
  3:
    up:
      update:
        command: "xdotool key XF86AudioRaiseVolume"
    down:
      update:
        command: "xdotool key XF86AudioLowerVolume"
```

**Comment by iberianpig** [comment]
Here is the configuration I use. By using [fusuma-plugin-keypress](https://github.com/iberianpig/fusuma-plugin-keypress) and [fusuma-plugin-sendkey] (https://github.com/iberianpig/fusuma-plugin-sendkey), you can set up volume control.

With the following settings, you can adjust the volume by swiping with three fingers while holding the ALT key. Swiping to the right increases the volume, and swiping to the left decreases it.

```yaml
swipe:
  3:
    right:
      update:
        keypress:
          LEFTALT:
            interval: 1
            sendkey: VOLUMEUP
            clearmodifiers: true

    left:
      update:
        keypress:
          LEFTALT:
            interval: 1
            sendkey: VOLUMEDOWN
            clearmodifiers: true
```
