### ISSUE TITLE
3-finger drag with word selection

### ISSUE THREAD

**Issue by rcambrj** [iberianpig/fusuma#333]
I have 3-finger drag configured as in https://github.com/iberianpig/fusuma/wiki/3-fingers-Drag-(OS-X-Style). Thank you so much for your hard work in making this software :)

However, this is missing one feature: double-3-finger tap then drag, which does two things:

* first selects the word under the cursor (like double primary button tap)
* then drags (like three-finger drag)

This allows the user to select whole words.

https://github.com/iberianpig/fusuma/issues/168 is a discussion about using 3-finger tap to select a word then look up that word in a dictionary. The solution hints at word selection:

```
tap:
  3:
    command: 'xdotool click --repeat 2 1 && xdg-open https://www.google.com/search?q="$(xsel -p)"'
```

I think the following configuration *might* work:

```
tap:
  3:
    command: 'xdotool click 1'
swipe:
  3:
    begin:
      command: xdotool mousedown 1
    update:
      command: xdotool mousemove_relative -- $move_x, $move_y
      interval: 0.01
      accel: 2
    end:
      command: xdotool mouseup 1
```

But I see that the https://github.com/iberianpig/fusuma-plugin-tap repository is archived and probably not maintained, so what is the future of the `tap` gesture? Is there an alternative which I should be using instead?
