### ISSUE TITLE
3 finger click question (This is not a bug, I just have a question where I don't know where to find the answer.)

### ISSUE THREAD

**Issue by luyanfeng** [iberianpig/fusuma#334]
这不是个bug, 我只是有个问题不知道在哪里找到答案.

我的系统三指点击会自动复制光标选中的内容然后进行粘贴.

我不知道怎么取消这个设置.

我最终的目的是想使用fusuma实现三指点击 进行翻译:

```
It's not a bug, I just have a question I don't know where to find the answer.

My system three-finger click will automatically copy the cursor selection and paste it.

I don't know how to undo this setting.

My ultimate goal is to use fusuma to implement three-finger click for translation:
```

ubuntu24.04  6.8.0-35-generic

```yml
tap:
  4:
    command: 'curl -XPOST 127.0.0.1:10835/translate -d "$(xsel -p)"'
```
