### ISSUE TITLE
Mouse Left & Right click hold not usable with hold:1 enabled

### ISSUE THREAD

**Issue by KAGEYAM4** [iberianpig/fusuma#340]
**Describe the bug**
With fusuma disabled. I can simulate Left mouse click hold and Right mouse click hold. But with fusuma enabled and having a config of hold:1, both left & right mouse click hold using touchpad triggers hold:1 config action.

**To Reproduce**
Mouse left click hold using touchpad (fusuma hold:1 disabled)

1. 1-finger-tap (down) then (up)
2. 1-finger-tap (down) and hold

Mouse Right lcick hold using touchpad (fusuma hold:1 disabled)
1. 2-finger-tap (down) then (up)
2. 1-finger-tap (down) and hold

With fusuma hold:1 enabled, both above produces hold:1 config action

**Expected behavior**
Mouse left & Right click hold to work alongside hold:1

**Versions**
```yml
I, [2025-03-05T07:04:15.646475 #89709]  INFO -- : reload config: /home/phoenix/.config/fusuma/config.yml
I, [2025-03-05T07:04:15.646515 #89709]  INFO -- : ---------------------------------------------
I, [2025-03-05T07:04:15.646665 #89709]  INFO -- : Fusuma: 3.7.0
I, [2025-03-05T07:04:15.647150 #89709]  INFO -- : libinput: 1.27.1
I, [2025-03-05T07:04:15.647170 #89709]  INFO -- : ruby 3.3.7p123
I, [2025-03-05T07:04:15.647684 #89709]  INFO -- : OS: Linux 6.13.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 27 Feb 2025 18:09:44 +0000
I, [2025-03-05T07:04:15.648196 #89709]  INFO -- : Distribution: \S{PRETTY_NAME} \r (\l)
I, [2025-03-05T07:04:15.649761 #89709]  INFO -- : Desktop session: wayland
I, [2025-03-05T07:04:15.649841 #89709]  INFO -- : ---------------------------------------------
I, [2025-03-05T07:04:15.649876 #89709]  INFO -- : Enabled Plugins:
I, [2025-03-05T07:04:15.649970 #89709]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2025-03-05T07:04:15.649980 #89709]  INFO -- :   Fusuma::Plugin::Buffers::TimerBuffer
I, [2025-03-05T07:04:15.650002 #89709]  INFO -- :   Fusuma::Plugin::Detectors::HoldDetector
I, [2025-03-05T07:04:15.650008 #89709]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2025-03-05T07:04:15.650032 #89709]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2025-03-05T07:04:15.650038 #89709]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2025-03-05T07:04:15.650044 #89709]  INFO -- :   Fusuma::Plugin::Events::Records::ContextRecord
I, [2025-03-05T07:04:15.650049 #89709]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2025-03-05T07:04:15.650055 #89709]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2025-03-05T07:04:15.650061 #89709]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2025-03-05T07:04:15.650067 #89709]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2025-03-05T07:04:15.650073 #89709]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2025-03-05T07:04:15.650079 #89709]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2025-03-05T07:04:15.650085 #89709]  INFO -- :   Fusuma::Plugin::Inputs::TimerInput
I, [2025-03-05T07:04:15.650091 #89709]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2025-03-05T07:04:15.650097 #89709]  INFO -- : ---------------------------------------------
```

**Configuration**
```yml
hold:
  1:
    command: "ydotool key 29:1 57:1 57:0 29:0"
    threshold: 0.2
  2:
    command: "ydotool key 1:1 1:0"
    threshold: 0.2
  3:
    command: "hyprswitch gui --mod-key super --key tab --max-switch-offset 0"
    threshold: 0.2

# use rotate for volume and brightness
# interval is time for you to continue gesture after lifting finger use for the above


threshold: 0.2
```
