### ISSUE TITLE
Two finger swipes

### ISSUE THREAD

**Issue by rubenwardy** [iberianpig/fusuma#37]
I can't seem to get two finger swiping working - the page scrolls instead

* **OS:** xubuntu 16.10
* **Fusuma version:** 0.3.2 

```
rubenwardy:~ $ xinput --list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ ETPS/2 Elantech Touchpad                	id=13	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Asus Wireless Radio Control             	id=7	[slave  keyboard (3)]
    ↳ Video Bus                               	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ USB Camera                              	id=10	[slave  keyboard (3)]
    ↳ Asus WMI hotkeys                        	id=11	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
```

libinput-debug-events

```
event5 	POINTER_MOTION   +1405.42s	-11.43/ 69.14
event5 	POINTER_MOTION   +1405.43s	 -8.89/ 48.97
event5 	POINTER_MOTION   +1405.45s	 -6.00/ 30.53
event5 	POINTER_MOTION   +1405.46s	 -5.17/ 24.82
event5 	POINTER_MOTION   +1405.47s	 -4.50/ 19.05
event5 	POINTER_AXIS     +1406.29s	vert -0.25* horiz -4.64*
event5 	POINTER_AXIS     +1406.30s	vert -0.25* horiz -4.89*
event5 	POINTER_AXIS     +1406.31s	vert -0.25* horiz -4.57*
event5 	POINTER_AXIS     +1406.33s	vert -0.31* horiz -4.32*
event5 	POINTER_AXIS     +1406.34s	vert -0.49* horiz -4.25*
event5 	POINTER_AXIS     +1406.35s	vert -0.68* horiz -4.38*
event5 	POINTER_AXIS     +1406.37s	vert -0.74* horiz -4.38*
event5 	POINTER_AXIS     +1406.38s	vert -0.80* horiz -4.25*
event5 	POINTER_AXIS     +1406.39s	vert -0.92* horiz -4.06*
event5 	POINTER_AXIS     +1406.40s	vert -0.98* horiz -3.87*
event5 	POINTER_AXIS     +1406.42s	vert -0.98* horiz -3.68*
event5 	POINTER_AXIS     +1406.43s	vert -0.98* horiz -3.43*
event5 	POINTER_AXIS     +1406.44s	vert -0.98* horiz -3.24*
event5 	POINTER_AXIS     +1406.45s	vert -0.98* horiz -3.75*
event5 	POINTER_AXIS     +1406.47s	vert -0.98* horiz -4.32*
event5 	POINTER_AXIS     +1406.48s	vert -0.98* horiz -4.00*
event5 	POINTER_AXIS     +1406.49s	vert -0.92* horiz -3.87*
event5 	POINTER_AXIS     +1406.51s	vert -0.80* horiz -3.87*
```

/usr/share/X11/xorg.list.d/20-natural-scrolling.conf

```
Section "InputClass"
        Identifier "Natural Scrolling"
	MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Option "VertScrollDelta" "-75"
        Option "HorizScrollDelta" "75"
        Option "DialDelta" "-75"
EndSection
```

Looks like I use Synaptics:

```
rubenwardy:~ $ dmesg | grep -i 'syna'
[    1.602604] psmouse serio4: elantech: Synaptics capabilities query result 0x10, 0x14, 0x0e.
```

config

```yml
swipe:
  2:
    left:
      shortcut: 'alt+Left'
    right:
      shortcut: 'alt+Right'
  3:
    left:
      shortcut: 'ctrl+alt+Right'
    right:
      shortcut: 'ctrl+alt+Left'
    down:
      shortcut: 'ctrl+alt+d'
  4:
    left:
      shortcut: 'ctrl+alt+Right'
    right:
      shortcut: 'ctrl+alt+Left'

pinch:
  in:
    shortcut: 'ctrl+plus'
  out:
     shortcut: 'ctrl+minus'

threshold:
  swipe: 0.01
  pinch: 0.01

interval:
  swipe: 1
  pinch: 1
```
