### ISSUE TITLE
assigning commands

### ISSUE THREAD

**Issue by tristan-k** [iberianpig/fusuma#50]
Is is possible to assign arbitrary commands to a specific gesture? For example [skippy-xd](https://github.com/hotice/webupd8/blob/master/skippy-xd-fix) to recreate a [mission-control](https://support.apple.com/de-de/HT204100) like overview.

```
swipe:
  4: 
    up: 
      shortcut: '/usr/local/bin/skippy-xd-fix' 
```
