### ISSUE TITLE
Pastes "a" or "s" when I swipe up or swipe down

### ISSUE THREAD

**Issue by augustin-b** [iberianpig/fusuma#54]
1. Run fusuma with example config:

```
swipe:
  3: 
    left: 
      shortcut: 'alt+Left'
    right: 
      shortcut: 'alt+Right'
    up: 
      shortcut: 'ctrl+t'
    down: 
      shortcut: 'ctrl+w'
  4:
    left: 
      shortcut: 'super+Left'
    right: 
      shortcut: 'super+Right'
    up: 
      shortcut: 'super+a'
    down: 
      shortcut: 'super+s'
pinch:
  in:
    shortcut: 'ctrl+plus'
  out:
     shortcut: 'ctrl+minus'

threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1
```

2. Open text editor

3. Swipe up

or

3. Press space bar

4. Swipe up immediately 

This will paste "a" instead of doing predefined shortcut.

**It just pastes "a" or "s" if you pressed any key before the gesture.**
