### ISSUE TITLE
feature request: configure number of fingers for pinch

### ISSUE THREAD

**Issue by chriskuech** [iberianpig/fusuma#82]
In config.yml, I would like to configure the number of fingers for pinch to close the feature gap with MacOS/Windows gesture support.

Current config.yml:
```yaml
pinch:
  in:
    shortcut: 'ctrl+plus'
  out:
     shortcut: 'ctrl+minus'
```

Proposed config.yml:
```yaml
pinch:
  2:
    in:
      shortcut: 'ctrl+plus'
    out:
      shortcut: 'ctrl+minus'
  4:
    in:
      shortcut: 'super'
    out:
      shortcut: 'super+a'
```
