### ISSUE TITLE
Alt+Escape and alt+shift+Escape don't do what I'd expect 

### ISSUE THREAD

**Issue by ptoner** [iberianpig/fusuma#94]
I'm using the following configuration (partial):

```
  3: 
    left: 
      command: 'xdotool key alt+Escape'
    right: 
      command: 'xdotool key alt+shift+Escape'
```

These do mostly what I'd expect but there's a small but significant difference between these actions and what happens when you manually press these key configurations. It re-displays the windows in seemingly random order. 

If I look at the fusumu event log I see the correct output. But it definitely doesn't have the same behavior as manually pressing the buttons. 

Can anyone think of why that might happen?

**Comment by ptoner** [comment]
Update:

It seems like capitalizing Alt makes it work the way I'd expect. Not sure why. Also not positive this is exactly true yet but using it for a minute or two it seems better.

```
  3: 
    left: 
      command: 'xdotool key Alt+Escape'
    right: 
      command: 'xdotool key Alt+Escape+shift'

```
